---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# The Python Programming Language: Numerical Python (NumPy)

In [0]:
import numpy as np


<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [2]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

<br>
Or just pass in a list directly

In [3]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [0]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [0]:
m.shape

<br>
`arange` returns evenly spaced values within a given interval.

In [4]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`reshape` returns an array with the same data with a new shape.

In [5]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [7]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

<br>
`resize` changes the shape and size of array in-place.

In [8]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [0]:
np.ones((3, 2))

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [0]:
np.zeros((2, 3))

<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [0]:
np.eye(3)

<br>
`diag` extracts a diagonal or constructs a diagonal array.

In [0]:
np.diag(y)

<br>
Create an array using repeating list (or see `np.tile`)

In [0]:
np.array([1, 2, 3] * 3)

<br>
Repeat elements of an array using `repeat`.

In [0]:
np.repeat([1, 2, 3], 3)

<br>
#### Combining Arrays

In [0]:
p = np.ones([2, 3], int)
p

<br>
Use `vstack` to stack arrays in sequence vertically (row wise).

In [0]:
np.vstack([p, 2*p])

<br>
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [0]:
np.hstack([p, 2*p])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [0]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

In [0]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

In [0]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [0]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

In [0]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [0]:
z = np.array([y, y**2])
z

<br>
The shape of array `z` is `(2,3)` before transposing.

In [0]:
z.shape

<br>
Use `.T` to get the transpose.

In [0]:
z.T

<br>
The number of rows has swapped with the number of columns.

In [0]:
z.T.shape

<br>
Use `.dtype` to see the data type of the elements in the array.

In [0]:
z.dtype

<br>
Use `.astype` to cast to a specific type.

In [0]:
z = z.astype('f')
z.dtype

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [0]:
a = np.array([-4, -2, 1, 3, 5])

In [0]:
a.sum()

In [0]:
a.max()

In [0]:
a.min()

In [0]:
a.mean()

In [0]:
a.std()

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [0]:
a.argmax()

In [0]:
a.argmin()

<br>
## Indexing / Slicing

In [0]:
s = np.arange(13)**2
s

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [0]:
s[0], s[4], s[-1]

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [0]:
s[1:5]

<br>
Use negatives to count from the back.

In [0]:
s[-4:]

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [0]:
s[-5::-2]

<br>
Let's look at a multidimensional array.

In [0]:
r = np.arange(36)
r.resize((6, 6))
r

<br>
Use bracket notation to slice: `array[row, column]`

In [0]:
r[2, 2]

<br>
And use : to select a range of rows or columns

In [0]:
r[3, 3:6]

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [0]:
r[:2, :-1]

<br>
This is a slice of the last row, and only every other element.

In [0]:
r[-1, ::2]

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [0]:
r[r > 30]

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [0]:
r[r > 30] = 30
r

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [0]:
r2 = r[:3,:3]
r2

<br>
Set this slice's values to zero ([:] selects the entire array)

In [0]:
r2[:] = 0
r2

<br>
`r` has also been changed!

In [0]:
r

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [0]:
r_copy = r.copy()
r_copy

<br>
Now when r_copy is modified, r will not be changed.

In [0]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [0]:
test = np.random.randint(0, 10, (4,3))
test

<br>
Iterate by row:

In [0]:
for row in test:
    print(row)

<br>
Iterate by index:

In [0]:
for i in range(len(test)):
    print(test[i])

<br>
Iterate by row and index:

In [0]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

<br>
Use `zip` to iterate over multiple iterables.

In [0]:
test2 = test**2
test2

In [0]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)